parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        public: false

    Alfred\Alfred\Infrastructure\UI\Console\Application:
        public: true


    Alfred\Alfred\Infrastructure\UI\Console\Command\:
        resource: '../src/Alfred/Infrastructure/UI/Console/Command'
        public: true
        tags: [alfred.command]

    Alfred\Alfred\Application\UseCase\CreateProjectUseCase:
        tags:
            - { name: tactician.handler, typehints: true }
